#!/usr/bin/env bash
# This script installs and configures nginx in a new Ubuntu server
sudo apt-get update

sudo apt-get install -y nginx

sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 80;
    server_name _;

    location / {
        echo "HTTP/1.1 200 OK";
        echo "Content-Type: text/html";
        echo "";
        echo "<html><body>Hello World!</body></html>";
    }
}
EOF
sudo service nginx restart
