#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but displays "Hi" on 9th iteration
i=0
while (( i < 10 ))
do
	echo "Best School"
	if [ $i -eq 8 ]
	then
		echo "Hi"
	fi
	(( i++ ))
done
