#!/usr/bin/env bash
#this is a script that creates an RSA key pair

if ! command -v openssl &> /dev/null; then
    echo "openssl is not installed. Please install openssl to use this script."
    exit 1
fi

openssl genpkey -algorithm RSA -out school.pem -aes256 -pass pass:betty -pkeyopt rsa_keygen_bits:4096

openssl rsa -in school.pem -outform PEM -out school.key -passin pass:betty

rm school.pem

echo "RSA key pair created successfully."
